dist: xenial  
language: python
python:
  - "3.7"
before_install:
  - psql -c "create user test with password 'test';" -U postgres
  - psql -c "create database orm_test;" -U postgres
  - psql -c "grant all privileges on database orm_test to test;" -U postgres
install:
  - make install
script:
  - make test
services: postgresql